package com.gabriel_codarcea.core.network.utils

const val LOGIN_RESPONSE_CODE_SUCCESS = 200
const val LOGIN_RESPONSE_CODE_UNAUTHORIZED = 401
const val LOGIN_RESPONSE_CODE_TOKEN_EXPIRED = 425
const val LOGIN_RESPONSE_BAD_RESPONSE = 600